### ISSUE TITLE
allow loading js file instead of json

### ISSUE THREAD

**Issue by ORESoftware** [lorenwest/node-config#508]
I have this file `local.js`:

```js
'use strict';

const config = require('./default.json');

if (process.env.luma_mongo_debug_logging === 'nope') {
	config.debug = false;
}

module.exports = config;
```

I want to allow env variables to dynamically change the config. I think this make it simpler to manage env variables.

I set:

```bash
export NODE_ENV='local';
```

and I use:

```js
const config = require('config');
```

But I get this error:

```
account-service: Error: Cannot parse config file: '/Users/oleg/codes/luma/account-service/config/local.js': SyntaxError: /Users/oleg/codes/luma/account-service/config/default.json: Unexpected token / in JSON at position 218
account-service:     at Config.util.parseFile (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:931:11)
account-service:     at /Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:702:28
account-service:     at Array.forEach (<anonymous>)
account-service:     at /Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:698:14
account-service:     at Array.forEach (<anonymous>)
account-service:     at Config.util.loadFileConfigs (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:697:13)
account-service:     at new Config (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:122:27)
```

We are on config version:
` "config": "^1.12.0",`

**Comment by ORESoftware** [comment]
Looking at the codebase, in version `2.x`, looks like you guys are checking the extension, and using require() to load the file if it ends with `.js`...so I think we need to bump our version.

**Comment by markstos** [comment]
@ORESoftware Sounds like you are saying "nevermind, the issue was resolved in the latest version", so I'm closing this issue now. If there seems to be a bug with the current version, let us know.

**Comment by ORESoftware** [comment]
just leave it open for a day

**Comment by ORESoftware** [comment]
@markstos as I suspected might happen, there has been a hiccup here. So I have this:

```bash
export NODE_ENV='local';
```

and

```js
const config = require('config');
```

and even with `config` version `2.0.1` I still get this error:

```
account-service: Error: Cannot parse config file: '/Users/oleg/codes/luma/account-service/config/local.js': SyntaxError: /Users/oleg/codes/luma/account-service/config/default.json: Unexpected token / in JSON at position 218
account-service:     at Config.util.parseFile (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:832:11)
account-service:     at /Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:594:28
account-service:     at Array.forEach (<anonymous>)
account-service:     at /Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:590:14
account-service:     at Array.forEach (<anonymous>)
account-service:     at Config.util.loadFileConfigs (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:589:13)
account-service:     at new Config (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:136:27)
account-service:     at Object.<anonymous> (/Users/oleg/codes/luma/luma-utils/node_modules/config/lib/config.js:1637:31)
account-service:     at Module._compile (internal/modules/cjs/loader.js:689:30)
account-service:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**perhaps this is an issue with removing comments from the JSON?**

**Comment by ORESoftware** [comment]
Oh lol, I see, I am causing that to happen, because I am calling `require('./json')` directly, back to the drawing board.

**Comment by vivek241** [comment]
@ORESoftware - JSON5 https://json5.org/

**Comment by iMoses** [comment]
@markstos this one can also be closed :)
